### ISSUE TITLE
with JS on it overwrites contributors

### ISSUE THREAD

**Issue by 01micko** [puppylinux-woof-CE/puppylinux-woof-CE.github.io#16]
If javascript is ON contributors are overwritten. I think this is a hangover of before we went serverside.

Since I have fixed styling of the table and screenshots (server side) I don't think we really need puppy.js (where contribs are loaded).

I'll do some experiments and see if we can get away from `c/puppy.js`.

**Comment by 01micko** [comment]
Ok, seems to work fine - but I'll leave this open in case someone finds a bug or there is a better way.

**Comment by 01micko** [comment]
We probably _really need_ someone else to contribute before we can call 'aye' or 'nay' on this one :smirk_cat:

**Comment by mavrothal** [comment]
> Ok, seems to work fine

How do you mean this? All pages have 
`Last updated 4 Mar 2016. Page contributors: 01micko, mavrothal.`
Is this the intended behaviour?

**Comment by 01micko** [comment]
Nope, not here; same in chromium and firefox (and netsurf fwiw)

![js](https://cloud.githubusercontent.com/assets/1019119/13547523/55dabd2a-e322-11e5-86d8-77895cd67cf6.jpg)

**Comment by 01micko** [comment]
Even works in xp / IE6

**Comment by L18L** [comment]
> We probably really need someone else to contribute before we can call 'aye' or 'nay' on this one :smirk_cat:

I read it: ninaholic has contributed to history (only).
Thus I say: **Aye** on this.

**Comment by jamesbond3142** [comment]
No, puppy.js is not a leftover. I included it because I could not do certain things without javascript.
Puppy.js serves three purposes:
a) to style the tables - which you have already overcome, so you can drop this part.
b) to update the "last modified date". If not enabled, it will take the date from the "updated" header. If you can find to get this info from kramdown (I tried page.date and it didn't work), feel free to drop this part.
c) to update the contributors list based on their commits. If not enabled, it will take the list from the "authors" header. Again, if you can find a way for kramdown to really get and show this info, feel free to drop it.

Alternatively, of course, drop the script, but remember to always maintain "updated" and "authors" field when somebody contributes.

**Comment by mavrothal** [comment]
nanaholic is there because was added manually as part of e15c8c9 the same is true for all the other contributions (for example James is missing from everywhere) Also if you see Screenshots that you updated a couple of hours ago in b9727b0 it still says updated March 4.
So unless you can get this info server side and pass it to header of the .md files, I would reactivate puppy.js. Alternatively you can do it manually or hope the contributor will do so.
Also if at the end you decide to reactivate the script I would drop the bogus last update and contributors info in the header of the md files (replace it with blank or a script related message) because sooner or latter will create issues.

**Comment by 01micko** [comment]
Ok, no problem, I'll close this.
